Repository maistra/proxy, pull requests merged in 2020-10, with the labels that each got.

#52 Pull in latest 1.6 changes from upstream
  .bazelversion
  WORKSPACE
  extensions/common/proto_util.cc
  extensions/common/proto_util_test.cc
  extensions/stackdriver/common/constants.h
  extensions/stackdriver/common/utils.cc
  extensions/stackdriver/common/utils.h
  extensions/stackdriver/metric/record.cc
  testdata/client_node_metadata.json.tmpl
  testdata/server_node_metadata.json.tmpl
  testdata/stackdriver/client_request_count.yaml.tmpl
  testdata/stackdriver/gce_client_request_count.yaml.tmpl
  testdata/stackdriver/gce_server_request_count.yaml.tmpl
  testdata/stackdriver/server_request_count.yaml.tmpl
Labels: okay to merge, size/L

#53 Add postsubmit job
  maistra/ci/post-submit.sh
  maistra/ci/pre-submit.sh
Labels: okay to merge, size/M

#54 Limit the postsubmit job to 4 threads
  .mergify.yml
  maistra/ci/post-submit.sh
Labels: okay to merge, size/M

#57 MAISTRA-1928: Update codebase with latest envoy changes
  WORKSPACE
  maistra/vendor/com_github_gperftools_gperftools/autom4te.cache/requests
  maistra/vendor/envoy/source/extensions/tracers/zipkin/tracer.cc
  maistra/vendor/envoy/source/extensions/transport_sockets/tls/context_config_impl.cc
  maistra/vendor/envoy/source/extensions/transport_sockets/tls/context_config_impl.h
  maistra/vendor/envoy/source/extensions/transport_sockets/tls/ssl_socket.cc
  maistra/vendor/envoy/test/extensions/tracers/zipkin/tracer_test.cc
Labels: okay to merge, size/XL

#59 Add CI capabilities for 1.1 branch, mostly copied from 2.0
  Makefile.overrides.mk
  maistra/Makefile
  maistra/ci/post-submit.sh
  maistra/ci/pre-submit.sh
  maistra/scripts/update-deps.sh
  maistra/scripts/update-envoy-sha.sh
  maistra/update-deps/Dockerfile
  maistra/update-deps/README.md
Labels: okay to merge, size/L
