Repository maistra/proxy, pull requests merged in 2020-07, with the labels that each got.

#33 MAISTRA-1562: Fix race with close occurring before disconnect
  src/envoy/http/jwt_auth/integration_test/http_filter_integration_test.cc
Labels: okay to merge

#41 MAISTRA-1648: Add CI script
  maistra/run-ci.sh
Labels: okay to merge, size/M

#42 MAISTRA-1651: Automate the sync between Envoy<->Proxy
  Makefile.overrides.mk
  maistra/Makefile
  maistra/scripts/update-deps.sh
  maistra/scripts/update-envoy-sha.sh
Labels: okay to merge, size/M

#44 MAISTRA-1651: Fix the usage of /work dir
  maistra/scripts/update-deps.sh
Labels: okay to merge, size/XS

#46 MAISTRA-1667: Remove builder-image
  maistra/builder-image/Dockerfile.maistra-1.2
  maistra/builder-image/Makefile
  maistra/builder-image/README.md
Labels: okay to merge, size/M
