Repository maistra/proxy, pull requests merged in 2021-01, with the labels that each got.

#73 MAISTRA-2060: Point to Red Hat Jira for issues
  .github/ISSUE_TEMPLATE/config.yml
  README.md
Labels: okay to merge, size/S

#72 MAISTRA-1169: Do not ignore some tests
  .bazelignore
Labels: okay to merge, size/XS

#75 Replaced local_resources with local_ram_resources and local_cpu_resou…
  maistra/ci/post-submit.sh
  maistra/ci/pre-submit.sh
Labels: okay to merge, size/XS

#76 CI: Tidy build output
  maistra/bazelrc
  maistra/ci/common.sh
  maistra/ci/post-submit.sh
  maistra/ci/pre-submit.sh
Labels: okay to merge, size/M

#80 Updates for building under scl devtoolset-9 environment
  maistra/ci/post-submit.sh
  maistra/ci/pre-submit.sh
  maistra/vendor/com_googlesource_chromium_v8/wee8/build/toolchain/__pycache__/wrapper_utils.cpython-36.pyc
  maistra/vendor/com_googlesource_chromium_v8/wee8/third_party/inspector_protocol/__pycache__/pdl.cpython-36.pyc
  maistra/vendor/config_validation_pip3/PyYAML-5.3.1-cp36-cp36m-linux_x86_64.whl
  maistra/vendor/config_validation_pip3/requirements.bzl
  maistra/vendor/configs_pip3/requirements.bzl
  maistra/vendor/headersplit_pip3/requirements.bzl
  maistra/vendor/kafka_pip3/requirements.bzl
  maistra/vendor/protodoc_pip3/PyYAML-5.3.1-cp36-cp36m-linux_x86_64.whl
  maistra/vendor/protodoc_pip3/requirements.bzl
  maistra/vendor/thrift_pip3/requirements.bzl
  maistra/vendor/thrift_pip3/thrift-0.13.0-py3-none-any.whl
Labels: okay to merge, size/S

#82 Run dependencies update script in devtools-9 scl environment
  maistra/scripts/update-deps.sh
Labels: okay to merge, size/XS

#83 Post-submit: Fix the WASM workaround
  maistra/ci/post-submit.sh
Labels: okay to merge, size/XS

#85 Testing: envoye2e tests are being executed now
  maistra/ci/pre-submit.sh
Labels: okay to merge, size/XS

#88 Build WASM extensions
  maistra/ci/common.sh
  maistra/ci/post-submit.sh
  maistra/ci/pre-submit.sh
Labels: do-not-merge/hold, size/L

#89 dummy
  README.md
Labels: size/XS

#91 Build WASM extensions
  maistra/ci/common.sh
  maistra/ci/post-submit.sh
  maistra/ci/pre-submit.sh
Labels: okay to merge, size/L

#94 Copy envoy-centos to GCS as well
  maistra/ci/post-submit.sh
Labels: okay to merge, size/XS

#95 MAISTRA-2109: Run go tests the same way upstream does
  maistra/ci/pre-submit.sh
Labels: okay to merge, size/XS
