Repository maistra/proxy, pull requests merged in 2024-07, with the labels that each got.

#284 Reinstate the libc++ config and minimise diffs wrt upstream
  .bazelrc
  WORKSPACE
  envoy.bazelrc
Labels: okay to merge, size/S

#289 Added pre-submit-envoy.sh script to run envoy's tests
  maistra/ci/pre-submit-envoy.sh
Labels: okay to merge, size/S

#290 Update Envoy and dependencies
  WORKSPACE
  maistra/vendor/envoy/bazel/proxy_wasm_cpp_host.patch
  maistra/vendor/envoy/bazel/repositories.bzl
  maistra/vendor/envoy/openssl/bazelrc
  maistra/vendor/proxy_wasm_cpp_host/bazel/BUILD
Labels: okay to merge, size/M

#292 Update Envoy and dependencies
  WORKSPACE
  maistra/vendor/envoy/source/extensions/transport_sockets/tls/context_config_impl.cc
Labels: okay to merge, size/M

#293 Update bazelrc parameter for s390x
  maistra/bazelrc
Labels: okay to merge, size/XS, ok-to-test

#294 Update Envoy and dependencies
  WORKSPACE
  maistra/vendor/envoy/bssl-compat/source/SSL_CTX_set_custom_verify.cc
  maistra/vendor/envoy/bssl-compat/source/test/test_ssl.cc
Labels: okay to merge, size/L

#296 Update envoy and dependencies
  WORKSPACE
  maistra/vendor/envoy/source/extensions/filters/listener/tls_inspector/tls_inspector.cc
  maistra/vendor/envoy/source/extensions/transport_sockets/tls/ssl_socket.cc
Labels: okay to merge, size/S

#297 Bump to upstream 1.20.8
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
  source/extensions/filters/http/istio_stats/istio_stats.cc
Labels: okay to merge, size/XS, tide/merge-method-merge
